# Generated by Django 4.2.23 on 2025-07-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("rollno", models.CharField(max_length=20, unique=True)),
                ("age", models.IntegerField()),
                ("class_name", models.CharField(max_length=20)),
                ("grade", models.CharField(max_length=5)),
            ],
        ),
    ]
